### ISSUE TITLE
Add option to ignore path

### ISSUE THREAD

**Issue by mboughaba** [danielstjules/jsinspect#17]
Hi,
Is there anyway to ignore files based on a path.
I usually have my tests under test directory, it would be great if I can do something like this in .jsinspectrc
```json
{
  "ignore": "test/"
}
```

**Comment by mboughaba** [comment]
after investigating the code, I figure out that we could simply add "test" in order to ignore everything under "test" directory.

```javascript
// Ignore node_modules by default, along with ignore arg
ignorePatterns = ['node_modules'];
if (program.ignore) {
  ignorePatterns.push(program.ignore);
}
```
so I could simply set my .jsinspect as
```json
{
  "ignore": "test"
}
```

**Comment by danielstjules** [comment]
Glad it worked! :)
