### ISSUE TITLE
ignore files in .gitignore ? 

### ISSUE THREAD

**Issue by juanpabloaj** [danielstjules/jsinspect#21]
is a good feature ignore the files and directories in `.gitignore` file ? 

normally .gitignore have files/directories like coverage, lib-cov, results, etc

**Comment by danielstjules** [comment]
Have you found this to be an issue? jsinspect only looks at .jsx and js files, and you can specify specific paths to ignore as well using the `--ignore` flag.

**Comment by juanpabloaj** [comment]
when I use istanbul over this repo, and run jsinspect, jsinspect take the coverage dir 

```bash
$ git clone git@github.com:danielstjules/jsinspect.git
$ istanbul cover _mocha -R spec spec
$ jsinspect | grep coverage
```

**Comment by zxqfox** [comment]
Just fyi: If you would go gitignore way you could use [ignore](https://www.npmjs.com/package/ignore) package ;-)

**Comment by danielstjules** [comment]
I don't think I'll be adding this functionality to jsinspect. It should be easy to workaround it though when specifying paths or ignore patterns :)
