### ISSUE TITLE
Regexp for file extensions

### ISSUE THREAD

**Issue by benoror** [danielstjules/jsinspect#22]
I have a Node.js CLI utility written with [tj/commander.js](https://github.com/tj/commander.js), which consist of **several executable files without extension**, with the form:
### ./myScript1

```
#!/usr/bin/env node
var program = require('commander');
...
```

---

These are ignored by jsinspect and I would like to have an option to include them, maybe even manually inside an array, something like:

```
{
  "threshold":     30,
  "identifiers":   true,
  "ignore":        "test|spec",
  "reporter":      "default",
  "suppress":      100,
  "include":        ['myScript1', 'myScript2', 'src/myScript3']
}
```

**Comment by danielstjules** [comment]
Thanks for the issue! I'm thinking being able to specify the file extensions as a string/pattern (js|jsx) or glob (*) would help work around this

**Comment by danielstjules** [comment]
Assuming this probably isn't an issue anymore, but any paths to files you explicitly provide to jsinspect will be parsed. So, assuming you add jsinspect as a script in your package.json, you could do: `jsinspect myscript1 myscript2 src/myscript3` :)
