### ISSUE TITLE
Extension for Atom

### ISSUE THREAD

**Issue by listepo** [danielstjules/jsinspect#23]
It would be useful to have an extension by [Atom](http://atom.io)

**Comment by danielstjules** [comment]
Wouldn't make sense to bundle support for an editor into this repository, but it could exist in a separate package! :) I don't personally use Atom, but these would at least help run jsinspect: https://atom.io/packages/process-palette https://atom.io/packages/script https://atom.io/packages/terminal-status

**Comment by mik01aj** [comment]
And why not create a linter using [`linter-plus`](https://github.com/AtomLinter/linter-plus)?
