### ISSUE TITLE
No "jsx" option support in .jsinspectrc

### ISSUE THREAD

**Issue by scottaddie** [danielstjules/jsinspect#32]
Executing the following command works wonderfully for including `.jsx` files:

```bat
jsinspect --jsx ./src/js
```
When I remove the `--jsx` switch from here to the `.jsinspectrc` file, the `.jsx` files are no longer included. Here's the config file I was using:

```json
{
	"identifiers": true,
    "ignore": "tests",
    "jsx": true,
	"reporter": "default",
	"suppress": 100,
	"threshold": 30
}
```

This feature doesn't seem to be supported in the config file. Is there any interest in supporting it? If so, I can work on a PR.

**Comment by danielstjules** [comment]
Oops, sorry about that! Just need to add the string 'jsx' to this line: https://github.com/danielstjules/jsinspect/blob/master/bin/jsinspect#L51
