### ISSUE TITLE
throws error if run as npm script

### ISSUE THREAD

**Issue by adekbadek** [danielstjules/jsinspect#40]
When I run `$ jsinspect <path>` directly from the command line, it works as expected. However when I run it as an npm script (`$ npm run jsinspect`)
```
"scripts": {
  "jsinspect": "jsinspect src/"
},
```
and matches are found, error is thrown:
```
 1 match found across 2 files

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/aborowski/.nvm/versions/node/v6.3.1/bin/node" "/Users/aborowski/.nvm/versions/node/v6.3.1/bin/npm" "run" "jsinspect"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 jsinspect: `jsinspect src/`
npm ERR! Exit status 1
```

**Comment by danielstjules** [comment]
Yup! That's intended. From https://github.com/danielstjules/jsinspect#integration 

> It's simple to run jsinspect on your library source as part of a build process. It will exit with an error code of 0 when no matches are found, resulting in a passing step, and a positive error code corresponding to its failure. For example, with Travis CI, you could add the following entries to your .travis.yml:

Notice the "Exist status 1". That allows the error to be detected by CI like travis so you can have builds pass/fail based on the result. :)

**Comment by adekbadek** [comment]
@danielstjules thanks for the quick response! What do you think about a `--noerror` flag, to make `npm script` use a bit more pleasant? I could try to PR if you're ok with the idea

**Comment by danielstjules** [comment]
@adekbadek Just ignore the exit code :)
``` javascript
"scripts": {
  "jsinspect": "jsinspect src/ || true"
},
```
