### ISSUE TITLE
Reexporting is not supported

### ISSUE THREAD

**Issue by timbset** [danielstjules/jsinspect#44]
I have this code:
```
export * as util from './util';
```
Checking of this files throws the `type of null` error
I fixed it by refactoring:
```
import * as util from './util';
export { util };
```
Anyway it will be great to fix it

**Comment by danielstjules** [comment]
Sorry! Updating ES6 support this week and looking to do a major rewrite. This has been fixed in master :)

**Comment by danielstjules** [comment]
Actually, I don't think `export * as util from './util';` is valid. Babel fails to transpile it as well. I think this should have been `export * from './util';`

**Comment by davidfirst** [comment]
I just came across the exact same issue. 
Babel actually supports it with stage-0 and stage-1. Here is a demo:
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2016%2Cstage-1&targets=&browsers=&builtIns=false&code=export%20*%20as%20fs%20from%20'fs'%3B

I've seen some projects using this syntax, and it'll be nice to support it.

Thank you for the great project!

**Comment by danielstjules** [comment]
My mistake, forgot to follow up :) Support was added https://github.com/danielstjules/jsinspect/blob/master/lib/parser.js#L26 The whole library has been rewritten, and a _much better_ 0.10 release can be expected today or tomorrow!

**Comment by danielstjules** [comment]
[0.10 released](https://github.com/danielstjules/jsinspect/releases/tag/0.10.0), and that indeed fixed it :)

**Comment by davidfirst** [comment]
Awesome! Thank you so much! 
I just tested it and it's working perfectly.
