### ISSUE TITLE
error: unknown option -m

### ISSUE THREAD

**Issue by ilyabreev** [danielstjules/jsinspect#46]
jsinspect 0.8.0 (windows)

`jsinspect -i --ignore "public|test|\/js" -m 3`

gives 

`error: unknown option '-m'`

According to the documentation `-m` sets min matches.

**Comment by danielstjules** [comment]
It works if you specify a path:
```
jsinspect -i --ignore "public|test|\/js" -m 3 .
```
I wonder if this is a bug with `commander`

**Comment by danielstjules** [comment]
Nevermind, the logic was in master and never published. Just bumped and released `0.9` :)
