### ISSUE TITLE
Should this match?

### ISSUE THREAD

**Issue by staff0rd** [danielstjules/jsinspect#47]
The same code (three lines) is located in the same file [here](https://github.com/pixijs/pixi.js/blob/6d6ae559919ad8017619b30adcb7d3c32935a2c2/src/core/textures/BaseTexture.js#L235-L238) and [here](https://github.com/pixijs/pixi.js/blob/6d6ae559919ad8017619b30adcb7d3c32935a2c2/src/core/textures/BaseTexture.js#L528-L532).

I ran `jsinspect -t 30 -i BaseTexture.js` against but I get no matches.  Is this expected?

**Comment by danielstjules** [comment]
The library was written before ES6 became popular. Looks like it could use some updating - sorry!

**Comment by danielstjules** [comment]
Fixed in https://github.com/danielstjules/jsinspect/commit/3d624097ad2dd790bf97e5532c18713cfd6279f2 thanks!
