### ISSUE TITLE
TypeError when using destructuring assignment syntax 

### ISSUE THREAD

**Issue by davidfirst** [danielstjules/jsinspect#53]
A code example
```
let b;
[, b] = [4, 5]
```
The Syntax is [valid](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), and Babylon parses it [correctly](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015-loose%2Cstage-0&targets=&browsers=&builtIns=false&code=let%20b%3B%0A%5B%2C%20b%5D%20%3D%20%5B4%2C%205%5D%0A). 

However, running it through the inspector, I get the following error:
> TypeError: Cannot read property 'type' of null
>     at Function.getChildren (/Users/***/node_modules/jsinspect/lib/nodeUtils.js:98:24)
>     at dfs (/Users/***/node_modules/jsinspect/lib/nodeUtils.js:47:17)
>     at Array.forEach (native)

Other than that, the new version looks great!

**Comment by danielstjules** [comment]
Fixed in https://github.com/danielstjules/jsinspect/commit/34613c8d5f18fb0c5157ca7cae1d8262f24f2c3b and about to publish a patch release, thanks! :)
