### ISSUE TITLE
Blowing up on large react projects

### ISSUE THREAD

**Issue by danielstjules** [danielstjules/jsinspect#60]
Those ASTs are pretty big 😅

**Comment by diegocr** [comment]
Yup... it seems to allocate up to 1.4GB of memory and then it halts execution here with:

`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

I'll love a c&p-detector made in C/C++ :-)

**Comment by danielstjules** [comment]
@diegocr You'll probably have more immediate luck with http://pmd.sourceforge.net/pmd-4.3.0/cpd.html :)

**Comment by diegocr** [comment]
Thanks for the prompt reply and advice @danielstjules!

I'm looking for something i can integrate as part of the code quality checks for my team, and i'm not sure if a dependency on JAVA is something they would like... personally i highly dislike it myself, but thanks again in any case :)

**Comment by gcazaciuc** [comment]
How about trying to increase the memory limit of the underlying NodeJS process( possible similar to https://futurestud.io/tutorials/node-js-increase-the-memory-limit-for-your-process ) ?

**Comment by danielstjules** [comment]
Small improvements:
* https://github.com/danielstjules/jsinspect/commit/95488aa6f1b5eb4cde23e14671e806820be8feb9
* https://github.com/danielstjules/jsinspect/commit/b3c23ca1c41c2ef2577954577dcf3f50b106f569

**Comment by danielstjules** [comment]
@diegocr @gcazaciuc Fixed in 0.12.6 :)

@ehg Runs just fine on `wp-calypso` now :)

**Comment by diegocr** [comment]
Thanks @danielstjules! I'll give it a try shortly.
